name: Snake

on:
  schedule:
    - cron: "17 2 * * *" # daily, off-peak
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: pekaboo
          template: classic
          base: header, activity, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css, scss, dockerfile, batchfile
          output: svg
          filename: dist/metrics.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
